---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

hideVersion: true

showStats: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: HomeLab

background:
  image: https://images.unsplash.com/photo-1711906303490-9bd52e105e85?q=80&w=3867&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

theme: dark # or light
color: neutral # Supported colors are: slate, gray, zinc, neutral, stone, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
cardBlur: md
headerStyle: clean

target: _blank # Possible options include _blank, _self, and _top

quicklaunch:
  searchDescriptions: true
  # hideInternetSearch: true
  showSearchSuggestions: true
  # hideVisitURL: true

layout:
  Snapshots:
    header: false
    tab: Analytics
    style: row
    columns: 2
  Infrastructure:
    # header: false
    tab: Services
    style: row
    columns: 3
  Docker Containers:
    # header: false
    tab: Services
    style: row
    columns: 3
  HomeLab:
    tab: Bookmarks
    style: row
    columns: 3
  IT:
    tab: Bookmarks
    style: row
    columns: 3
  Social:
    tab: Bookmarks
    style: row
    columns: 3
  Cybersecurity:
    tab: Bookmarks
    style: row
    columns: 3